from langchain_community.utilities import SQLDatabase
from langchain_openai import ChatOpenAI
import os
from dotenv import load_dotenv

load_dotenv()

client = ChatOpenAI(api_key=os.getenv("OPENAI_API_KEY"), model="gpt-4.1-nano")

# db_con = SQLDatabase.from_uri("mysql+pymysql://<username>:<pwd>@<host_name>:<port_num>/<db_name>")
db_con = SQLDatabase.from_uri("mysql+pymysql://root:welcome@localhost:3306/sales")

my_schema = db_con.get_table_info()

while True:
    user_prompt = input ("\nEnter your prompt: ")
    if user_prompt == "exit":
        break

    my_prompt = f'''
    You are a helpful assistant that converts natural language to SQL for MySQL Database.
    Database Schema : {my_schema}
    Question : {user_prompt}

    Provide only SQL Query. Dont add anything before or after the SQL.
    '''

    response = client.invoke(my_prompt)
    my_sql = response.content
    print("\nSQL generated by LLM:\n")
    print(f"{my_sql} \n")

    print("RESULT:\n")
    results = db_con.run(my_sql)
    print(results)
